import { Counter } from '@/components/Counter';
import { GetServerSideProps } from 'next';
import Head from 'next/head';

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  return { props: {} };
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        Aptabase + Next.js Pages Router <br />
        <Counter />
      </main>
    </>
  );
}
